import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { CATEGORY_ORDER } from "@/config/categories";

const ROOT = process.cwd();

/**
 * The surfaces an agent uses to find UI Beats without a human in the loop: the
 * `Link: rel="alternate"` header on every component page, and the MCP server
 * card at `/.well-known/mcp.json`.
 */
describe("markdown alternate link", () => {
  const config = fs.readFileSync(path.join(ROOT, "next.config.mjs"), "utf8");

  /*
   * `next.config.mjs` cannot import `config/categories.ts`, so the category
   * alternation is spelled out there by hand. This is the guard that keeps the
   * copy honest: add a seventh category and the header silently stops applying
   * to it, which is exactly the kind of omission nobody notices.
   */
  it("advertises the markdown twin for every real category", () => {
    const match = config.match(/const COMPONENT_CATEGORIES = "([^"]+)"/);
    expect(match).not.toBeNull();

    const declared = match![1]!.split("|").sort();
    expect(declared).toEqual([...CATEGORY_ORDER].sort());
  });

  /*
   * `getting-started` pages have no markdown twin — `app/md/[category]/
   * [component]` builds its params from the registry and sets
   * `dynamicParams = false`, so advertising one would point agents at a 404.
   */
  it("does not match the getting-started section", () => {
    const match = config.match(/const COMPONENT_CATEGORIES = "([^"]+)"/);
    expect(match![1]!.split("|")).not.toContain("getting-started");
  });

  it("uses a relative URI so previews do not link to production", () => {
    expect(config).toContain(
      '</docs/:category/:component.md>; rel="alternate"; type="text/markdown"',
    );
    expect(config).not.toContain("https://uibeats.com/docs/:category");
  });
});

describe("mcp server card", () => {
  const cardPath = path.join(ROOT, "public", ".well-known", "mcp.json");

  // Generated by `yarn registry:build`, which `yarn build` runs first. Skipped
  // rather than failed when absent, so a bare `yarn test` on a fresh clone does
  // not report a build artifact as a broken test.
  const maybe = fs.existsSync(cardPath) ? it : it.skip;

  maybe("describes the published stdio package, not a remote endpoint", () => {
    const card = JSON.parse(fs.readFileSync(cardPath, "utf8"));

    expect(card.name).toBe("com.uibeats/mcp");
    // Reverse-DNS with exactly one slash, per the MCP server schema.
    expect(card.name.split("/")).toHaveLength(2);
    expect(card.remotes).toBeUndefined();

    const [pkg] = card.packages;
    expect(pkg.registryType).toBe("npm");
    expect(pkg.identifier).toBe("@uibeats/mcp");
    expect(pkg.transport).toEqual({ type: "stdio" });
  });

  maybe("stays in step with the version that actually shipped", () => {
    const card = JSON.parse(fs.readFileSync(cardPath, "utf8"));
    const pkg = JSON.parse(
      fs.readFileSync(
        path.join(ROOT, "packages", "mcp", "package.json"),
        "utf8",
      ),
    );

    expect(card.version).toBe(pkg.version);
    expect(card.packages[0].version).toBe(pkg.version);
    // A range here would let a client resolve a build the card never described.
    expect(card.packages[0].version).toMatch(/^\d+\.\d+\.\d+/);
  });
});
